backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "test"
    label: "Test"
    files:
      - file: "data/test.json"
        label: "Archivo de prueba"
        name: "archivo_test"
        format: "json"
        fields:
          - { label: "Título", name: "titulo", widget: "string" }
