backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "rotiseria"
    label: "Productos Rotisería"
    files:
      - file: "data/productos-rotiseria.json"
        label: "Lista de productos Rotisería"
        name: "productos_rotiseria"
        format: "json"
        fields:
          - label: "Categorías"
            name: "categorias"
            widget: list
            fields:
              - { label: "Nombre", name: "categoria", widget: "string" }
              - label: "Productos"
                name: "productos"
                widget: list
                fields:
                  - { label: "Nombre", name: "nombre", widget: "string" }
                  - { label: "Precio", name: "precio", widget: "number", value_type: "int" }
                  - { label: "Descripción", name: "desc", widget: "string", required: false }

  - name: "almacen"
    label: "Productos Almacén"
    files:
      - file: "data/productos-almacen.json"
        label: "Lista de productos Almacén"
        name: "productos_almacen"
        format: "json"
        fields:
          - label: "Categorías"
            name: "categorias"
            widget: list
            fields:
              - { label: "Nombre", name: "categoria", widget: "string" }
              - label: "Productos"
                name: "productos"
                widget: list
                fields:
                  - { label: "Nombre", name: "nombre", widget: "string" }
                  - { label: "Precio", name: "precio", widget: "number", value_type: "int" }
                  - { label: "Descripción", name: "desc", widget: "string", required: false }
