backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "rotiseria"
    label: "Productos Rotisería"
    label_singular: "Producto"
    folder: ""
    files:
      - file: "productos-rotiseria.json"
        label: "Lista de productos de rotisería"
        name: "productos_rotiseria"
        format: "json"
        fields:
          - label: Categorías
            name: categorias
            widget: list
            fields:
              - {label: "Nombre", name: "label", widget: "string"}
              - label: Productos
                name: productos
                widget: list
                fields:
                  - {label: "Nombre", name: "nombre", widget: "string"}
                  - {label: "Precio", name: "precio", widget: "number"}
                  - {label: "Descripción", name: "desc", widget: "string", required: false}

  - name: "almacen"
    label: "Productos Almacén"
    label_singular: "Producto"
    folder: ""
    files:
      - file: "productos-almacen.json"
        label: "Lista de productos de almacén"
        name: "productos_almacen"
        format: "json"
        fields:
          - label: Categorías
            name: categorias
            widget: list
            fields:
              - {label: "Nombre", name: "label", widget: "string"}
              - label: Productos
                name: productos
                widget: list
                fields:
                  - {label: "Nombre", name: "nombre", widget: "string"}
                  - {label: "Precio", name: "precio", widget: "number"}
                  - {label: "Descripción", name: "desc", widget: "string", required: false}
