backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "rotiseria"
    label: "Productos Rotisería"
    files:
      - file: "data/productos-rotiseria.json"
        label: "Lista de productos Rotisería"
        name: "productos_rotiseria"
        format: "json"
        fields:
          - label: "Categorías"
            name: "categorias"
            widget: "list"
            fields:
              - { label: "Nombre", name: "categoria", widget: "string" }
              - label: "Productos"
                name: "productos"
                widget: "list"
                fields:
                  - { label: "Nombre", name: "nombre", widget: "string" }
                  - { label: "Precio", name: "precio", widget: "number", value_type: "int" }
                  - { label: "Descripción", name: "desc", widget: "string", required: false }

  - name: "almacen"
    label: "Productos Almacén"
    files:
      - file: "data/productos-almacen.json"
        label: "Lista de productos Almacén"
        name: "productos_almacen"
        format: "json"
        fields:
          - label: "Categorías"
            name: "categorias"
            widget: "list"
            fields:
              - { label: "Nombre", name: "categoria", widget: "string" }
              - label: "Productos"
                name: "productos"
                widget: "list"
                fields:
                  - { label: "Nombre", name: "nombre", widget: "string" }
                  - { label: "Precio", name: "precio", widget: "number", value_type: "int" }
                  - { label: "Descripción", name: "desc", widget: "string", required: false }

  # ===== Promos =====
  - name: "promos_rotiseria"
    label: "Promos Rotisería"
    files:
      - file: "data/promos-rotiseria.json"
        label: "Listado de Promos (Rotisería)"
        name: "promos_rotiseria_file"
        format: "json"
        fields:
          - label: "Promos"
            name: "promos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Precio promo", name: "precio", widget: "number", value_type: "int" }
              - { label: "Precio original (tachado)", name: "precio_original", widget: "number", value_type: "int", required: false }
              - { label: "Etiqueta (badge)", name: "tag", widget: "string", required: false, hint: "Ej: Combo, 2x1, -20%" }
              - { label: "Descripción", name: "desc", widget: "string", required: false }
              - { label: "Vigencia hasta", name: "vigencia_hasta", widget: "date", format: "YYYY-MM-DD", required: false }

  - name: "promos_almacen"
    label: "Promos Almacén"
    files:
      - file: "data/promos-almacen.json"
        label: "Listado de Promos (Almacén)"
        name: "promos_almacen_file"
        format: "json"
        fields:
          - label: "Promos"
            name: "promos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "nombre", widget: "string" }
              - { label: "Precio promo", name: "precio", widget: "number", value_type: "int" }
              - { label: "Precio original (tachado)", name: "precio_original", widget: "number", value_type: "int", required: false }
              - { label: "Etiqueta (badge)", name: "tag", widget: "string", required: false, hint: "Ej: Pack, -12%" }
              - { label: "Descripción", name: "desc", widget: "string", required: false }
              - { label: "Vigencia hasta", name: "vigencia_hasta", widget: "date", format: "YYYY-MM-DD", required: false }
